Repository Debate-Season/DebateSeason_Frontend_V1, pull requests merged in 2025-02, with the labels that each got.

#68 feat : chatting UI/기능 구현
  lib/core/services/web_socket/stomp_service.dart
  lib/features/category/presentation/views/category_screen.dart
  lib/features/chat/bindings/chat_binding.dart
  lib/features/chat/data/data_sources/chat_rooms_messages_data_source.dart
  lib/features/chat/data/data_sources/chat_rooms_messages_data_source.g.dart
  lib/features/chat/data/mappers/chat_room_message_mapper.dart
  lib/features/chat/data/models/response/chat_messages_res.dart
  lib/features/chat/data/models/response/chat_messages_res.g.dart
  lib/features/chat/data/models/response/chat_msg_res.dart
  lib/features/chat/data/models/response/chat_room_messages_res.dart
  lib/features/chat/data/models/response/chat_room_messages_res.g.dart
  lib/features/chat/data/models/response/msg_new_res.dart
  lib/features/chat/data/models/response/msg_new_res.g.dart
  lib/features/chat/data/repository_impls/chat_rooms_messages_repository_impl.dart
  lib/features/chat/domain/entities/chat_message_cursor_entity.dart
  lib/features/chat/domain/entities/chat_message_cursor_entity.freezed.dart
  lib/features/chat/domain/entities/chat_message_entity.dart
  lib/features/chat/domain/entities/chat_message_entity.freezed.dart
  lib/features/chat/domain/entities/chat_message_entity.g.dart
  lib/features/chat/domain/entities/chat_room_message_entity.dart
  lib/features/chat/domain/entities/chat_room_message_entity.freezed.dart
  lib/features/chat/domain/repositories/chat_rooms_messages_repository.dart
  lib/features/chat/presentation/types/chat_message_type.dart
  lib/features/chat/presentation/types/opinion_type.dart
  lib/features/chat/presentation/view/chat_room_screen.dart
  lib/features/chat/presentation/view/debate_room_screen.dart
  lib/features/chat/presentation/view_model/chat_room_view_model.dart
  lib/features/chat/presentation/widgets/chat_message.dart
  lib/features/chat/presentation/widgets/chat_room_app_bar.dart
  lib/features/issue/presentation/view/issue_room_screen.dart
  lib/widgets/de_scaffold.dart
Labels: Feat, 채팅

#72 fix : 프로필 관련 이슈 처리
  lib/features/auth/bindings/auth_binding.dart
  lib/features/auth/presentation/view_models/auth_view_model.dart
  lib/features/auth/presentation/views/auth_screen.dart
  lib/features/profile/presentation/views/profile_input_page.dart
  lib/features/profile/presentation/views/profile_screen.dart
  lib/features/profile/presentation/views/profile_withdraw_page.dart
Labels: Fix, 로그인, 프로필

#75 fix #74 선택되어있는 찬반 선택시 작동하지않도록 수정
  lib/features/chat/presentation/types/opinion_type.dart
  lib/features/chat/presentation/view/debate_room_screen.dart
Labels: Fix, 토론

#86 refactor : dev/prod env 분리
  lib/main.dart
  pubspec.yaml
Labels: Refactor

#82 mod : DeAppBar 통일
  lib/features/auth/presentation/views/auth_screen.dart
  lib/features/category/presentation/views/category_screen.dart
  lib/features/chat/presentation/view/chat_room_screen.dart
  lib/features/chat/presentation/view/debate_room_screen.dart
  lib/features/chat/presentation/widgets/chat_room_app_bar.dart
  lib/features/chat/presentation/widgets/debate_app_bar.dart
  lib/features/issue/presentation/view/issue_room_screen.dart
  lib/features/issue/presentation/widgets/issue_app_bar.dart
  lib/features/profile/presentation/views/profile_input_page.dart
  lib/features/profile/presentation/views/profile_screen.dart
  lib/features/profile/presentation/views/profile_withdraw_page.dart
  lib/widgets/de_app_bar.dart
Labels: Mod, 공통

#89 refactor : Auth, Category에서 뒤로가기시 토스트메시지 출력
  lib/features/auth/presentation/views/auth_screen.dart
  lib/features/category/presentation/views/category_screen.dart
  lib/utils/exit_app_util.dart
Labels: Refactor, 공통

#90 refactor : 코드 스타일 및 명명 규칙 개선
  ios/Runner.xcodeproj/project.pbxproj
  lib/core/constants/color.dart
  lib/core/constants/de_colors.dart
  lib/core/constants/de_dimensions.dart
  lib/core/constants/de_fonts.dart
  lib/core/constants/de_gaps.dart
  lib/core/constants/de_icons.dart
  lib/core/constants/icons.dart
  lib/core/constants/text_style.dart
  lib/core/routers/get_router.dart
  lib/features/auth/presentation/views/auth_screen.dart
  lib/features/category/presentation/views/category_screen.dart
  lib/features/chat/bindings/chat_binding.dart
  lib/features/chat/bindings/debate_binding.dart
  lib/features/chat/debate_constants.dart
  lib/features/chat/presentation/view_models/chat_room_view_model.dart
  lib/features/chat/presentation/view_models/debate_room_view_model.dart
  lib/features/chat/presentation/views/chat_room_screen.dart
  lib/features/chat/presentation/views/debate_room_screen.dart
  lib/features/chat/presentation/widgets/change_popup.dart
  lib/features/chat/presentation/widgets/chat_bottom_sheet.dart
  lib/features/chat/presentation/widgets/chat_input_field.dart
  lib/features/chat/presentation/widgets/chat_message.dart
  lib/features/issue/bindings/issue_binding.dart
  lib/features/issue/issue_constants.dart
  lib/features/issue/presentation/view_models/issue_room_view_model.dart
  lib/features/issue/presentation/views/issue_room_screen.dart
  lib/features/issue/presentation/widgets/issue_card.dart
  lib/features/profile/presentation/views/profile_input_page.dart
  lib/features/profile/presentation/views/profile_screen.dart
  lib/features/profile/presentation/views/profile_withdraw_page.dart
  lib/features/profile/presentation/widgets/profile_age_bottom_sheet.dart
  lib/features/profile/presentation/widgets/profile_community_bottom_sheet.dart
  lib/features/profile/presentation/widgets/profile_community_card.dart
  lib/features/profile/presentation/widgets/profile_gender_card.dart
  lib/features/profile/presentation/widgets/profile_text_card.dart
  lib/main.dart
  lib/utils/de_snack_bar.dart
  lib/utils/de_toast.dart
  lib/widgets/de_app_bar.dart
  lib/widgets/de_bottom_sheet.dart
  lib/widgets/de_button_large.dart
  lib/widgets/de_button_small.dart
  lib/widgets/de_cached_image.dart
  lib/widgets/de_dialog.dart
  lib/widgets/de_progress_indicator.dart
  lib/widgets/de_scaffold.dart
  lib/widgets/de_text_field.dart
Labels: Refactor, 공통

#96 hotfix : TestFlight 배포 에러 [ITMS-91061: Missing privacy manifest]
  ios/Podfile.lock
  ios/Runner/Runner.entitlements
  pubspec.lock
  pubspec.yaml
Labels: Fix

#97 refactor : 로직 구조 및 안정성 개선
  lib/features/chat/presentation/view_models/chat_room_view_model.dart
  lib/features/chat/presentation/view_models/debate_ratio_view_model.dart
  lib/features/chat/presentation/view_models/debate_room_view_model.dart
  lib/features/chat/presentation/views/debate_room_screen.dart
  lib/features/chat/presentation/widgets/chat_input_field.dart
  lib/features/issue/issue_constants.dart
  lib/features/issue/presentation/view_models/issue_ratio_view_model.dart
  lib/features/issue/presentation/view_models/issue_room_view_model.dart
  lib/features/issue/presentation/views/issue_room_screen.dart
  lib/features/issue/presentation/widgets/issue_card.dart
Labels: Refactor, 채팅, 이슈, 토론

#99 fix : 채팅방 앱바 타이틀 정렬이 iOS와 android가 다른 현상
  lib/features/chat/presentation/views/chat_room_screen.dart
  lib/widgets/de_app_bar.dart
Labels: Fix, 채팅, 공통
