Repository Debate-Season/DebateSeason_Frontend_V1, pull requests merged in 2025-06, with the labels that each got.

#151 fix : pip 개선
  assets/icons/ic_article_grey10.svg
  assets/icons/ic_comm_grey10.svg
  assets/icons/ic_copy_grey10.svg
  assets/icons/ic_youtube_grey10.svg
  assets/icons/ic_youtube_logo_grey50.svg
  lib/core/constants/de_icons.dart
  lib/core/services/pip_controller.dart
  lib/features/home/presentation/views/home_media_page.dart
  lib/features/home/presentation/views/live_all_page.dart
  lib/main.dart
  lib/widgets/de_pip.dart
  pubspec.lock
  pubspec.yaml
Labels: Fix, 홈

#149 fix : 로그인 버튼 변경 및 프로필 아이콘 제거
  assets/icons/ic_apple_login.svg
  assets/icons/ic_kakao_login.svg
  assets/icons/ic_login_apple.svg
  assets/icons/ic_login_kakao.svg
  lib/core/constants/de_icons.dart
  lib/features/auth/auth_constants.dart
  lib/features/auth/presentation/views/auth_screen.dart
  lib/features/issuemap/presentation/views/issuemap_screen.dart
Labels: Fix, 로그인

#152 feat : 미디어 무한스크롤 개선
  assets/images/img_media_thumbnail.png
  lib/features/home/presentation/view_models/media_view_model.dart
  lib/features/home/presentation/views/home_media_page.dart
Labels: Feat, 홈

#157 fix : 4차 스프린트 UI 수정
  lib/features/home/presentation/views/home_screen.dart
  lib/features/issue/data/models/response/chat_room_res.dart
  lib/features/issue/data/models/response/chat_room_res.g.dart
  lib/features/issue/domain/entities/chat_room_entity.dart
  lib/features/issue/issue_constants.dart
  lib/features/issue/presentation/widgets/issue_card.dart
  lib/features/issuemap/presentation/views/issuemap_screen.dart
  lib/main.dart
Labels: Fix, 이슈, 토론, 이슈맵, 홈

#156 feat : 내프로필 UI 변경 및 커뮤니티 이용가이드 웹뷰 연결
  lib/features/profile/presentation/views/profile_screen.dart
  lib/features/profile/profile_constants.dart
Labels: Feat, 프로필
